### ISSUE TITLE
RLScore didn't work with python>=3.7

### ISSUE THREAD

**Issue by rkdarst** [aatapa/RLScore#8]
We saw two problems when trying to help someone install RLScore on our cluster (I was helping someone install it).  I think these are solved by the latest commits 0d735a1 and 7d00dfc wich has cython re-run on every install.

If anyone is reading this, installing directly from Github might work, but I haven't tested this yet: `pip install https://github.com/aatapa/RLScore/archive/refs/heads/master.zip`.  (until PyPI is updated).

Is there anything we can do to help?

The problems I saw, for searchability of anyone coming later:

- longintrepr.h not found -> this seemed to be moved in Python 3.11 and it says in the changelog it's been moved and shouldn't be used (since they are in Python.h): https://docs.python.org/3/whatsnew/changelog.html#id197  .  Downgrading to python 3.10 worked.

- Some changes in PyThreadState (exc_type, exc_value, exc_traceback).  I saw something in the Python changelog semi-related, but it was a change in 3.11 (which we already weren't using).  With trial and error, downgrading version-by-version, we found that Python 3.6 worked.  Unfortunately I can't link to the exact problem.  Some error messages below.
```
      rlscore/utilities/swapped.c:8376:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
       8376 |     tstate->exc_value = local_value;
            |             ^~~~~~~~~
            |             curexc_value
      rlscore/utilities/swapped.c:8377:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
       8377 |     tstate->exc_traceback = local_tb;
            |             ^~~~~~~~~~~~~
            |             curexc_traceback
      error: command 'gcc' failed with exit status 1
```

**Comment by RiikkaHuu** [comment]
> If anyone is reading this, installing directly from Github might work, but I haven't tested this yet: pip install https://github.com/aatapa/RLScore/archive/refs/heads/master.zip. (until PyPI is updated).

Tried this installation approach with python 3.9, however there were some issues. Namely, I got errors:

``` 
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          inf = float('Inf')
      
          for newclazz in range(labelcount):
      
              #!!!!!!!!!!!!!!!
              takenum = (size / labelcount) - classcounts[newclazz] + howmany
                                                                    ^
      ------------------------------------------------------------
      
      rlscore/learner/_steepest_descent_mmc.pyx:55:62: Cannot assign type 'double' to 'int'
```

Using float division (i.e. `(size // labelcount)`) got rid of the error, but I'm not sure if this was the correct way to fix this or not.
